contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
  packages:
    ## Base set of packages
    - alpine-baselayout-data
    - ca-certificates-bundle

accounts:
  groups:
    - groupname: bsides
      gid: 101
  users:
    - username: bsides
      uid: 100
      gid: 101

archs:
 - amd64
